language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  directories:
    - /home/travis/.rustup
    - /home/travis/.cargo
    - /home/travis/target

env:
  - CRATE=im
  - CRATE=im-rc

install:
  - mkdir -p .cargo && echo '[build]' > .cargo/config && echo 'target-dir = "/home/travis/target"' >> .cargo/config
  - cargo install cargo-make; true
  - cargo make prepare-release

script: cd dist/$CRATE; cargo test

matrix:
  include:
    - env: CLIPPY=1
      rust: stable
      install:
        - rustup component add clippy; true
      script: cargo clippy -- -D warnings
