language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  directories:
    - /home/travis/.cargo
install:
  - rustup toolchain add nightly
script:
  - cargo +nightly rustc --features clippy -- -D warnings
  - cargo test
