language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  directories:
    - /home/travis/.cargo
install:
  - rustup toolchain add nightly
  - rustup component add --toolchain nightly clippy-preview; true
script:
  - cargo +nightly clippy -- -D warnings
  - cargo test
  - cargo clean
  - IM_TEST_RC=1 cargo test
  - ./build-releases.sh
  - cd im-rc; cargo test --tests
